import fs from 'node:fs';
import additionalPages from './pages.mjs';
const brand='Steady &amp; True';
const pages={
home:{title:'Relationship Coaching for Men',description:'Build stronger relationships without losing yourself. Relationship coaching for men with Josh Barbee.',body:`
<section class="hero"><div class="hero-copy"><p class="eyebrow light">RELATIONSHIP COACHING FOR MEN</p><h1>Strong in yourself.<br><em>Better together.</em></h1><p class="hero-description">Become the man you want to be in the relationships that matter most.</p><p class="hero-detail">Practical coaching with Josh Barbee for men ready to communicate honestly, show up fully, and build something real.</p><a class="button lime" href="/coaching/">Explore the coaching</a><a class="text-link pale" href="/approach/">Get to know the approach</a><div class="hero-signoff"><span class="mini-mark" aria-hidden="true">s&t</span><span>GROUNDED IN RESPECT.<br>BUILT FOR REAL LIFE.</span></div></div><div class="hero-photo"><div class="photo-caption"><span>A LITTLE MORE GROUNDED.</span><span>A LOT MORE CONNECTED.</span></div></div></section>
<div class="belief-strip"><span>Self-awareness</span><span aria-hidden="true">✳</span><span>Honest communication</span><span aria-hidden="true">✳</span><span>Mutual respect</span><span aria-hidden="true">✳</span><span>Everyday courage</span></div>
<section class="section introduction"><div><p class="eyebrow">A DIFFERENT KIND OF STRENGTH</p><h2>You don’t need all the answers.<br>Just a willingness to grow.</h2></div><div class="intro-copy"><p>Maybe hard conversations turn into arguments. Maybe you go quiet when things get real. Or maybe life looks good on paper, but your relationships feel distant.</p><p>You can learn a different way to show up. One rooted in confidence, care, and responsibility—for yourself and the people you love.</p><a class="text-link" href="/approach/">What healthy masculinity means here</a></div></section>
<section class="section focus-section"><div class="section-heading"><div><p class="eyebrow">THE WORK THAT MAKES A DIFFERENCE</p><h2>Good relationships.<br>Learnable skills.</h2></div><p>Small shifts in how you show up.<br>Meaningful changes in how you connect.</p></div><div class="focus-grid"><article><span class="number">01 / KNOW YOURSELF</span><h3>Understand what’s<br>under the surface.</h3><p>Recognize your patterns, name what you feel, and get clear on the values you want to live by.</p></article><article><span class="number">02 / SAY WHAT MATTERS</span><h3>Make room for<br>honest conversations.</h3><p>Speak clearly, listen with curiosity, and set boundaries that respect both you and the other person.</p></article><article><span class="number">03 / SHOW UP DIFFERENTLY</span><h3>Turn good intentions<br>into everyday action.</h3><p>Practice accountability, navigate disagreement, and follow through in the moments that count.</p></article></div></section>
<section class="quote-band"><p>“Strength is being someone you can count on.<br>Including when it’s hard.”</p><span>THE STEADY &amp; TRUE PHILOSOPHY</span></section>
<section class="section coach-intro"><div class="coach-label"><span class="eyebrow">YOUR COACH</span><h2>Josh Barbee</h2><p>Honest conversations.<br>Practical next steps.<br>Space to be yourself.</p></div><div><h3>A place to do the work,<br>without putting on an act.</h3><p>Steady &amp; True is built around a simple idea: healthy masculinity makes room for both strength and vulnerability. Coaching is a place to explore what that looks like in your life and relationships.</p><a class="text-link" href="/coaching/">See how coaching works</a></div></section>
${cta('A stronger connection starts with you.','You don’t have to have it all figured out to take the first step.')}`}
};
function cta(title,desc){return `<section class="cta"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>${title}</h2><p>${desc}</p></div><a class="button lime" href="/start/">Find your starting point</a></section>`}
function render(key,p){const links=[['home','/','Home'],['approach','/approach/','Our approach'],['coaching','/coaching/','Coaching']];return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#173c32"><meta name="description" content="${p.description}"><title>${p.title} | Steady &amp; True</title><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='20' fill='%23173c32'/%3E%3Ctext x='20' y='28' text-anchor='middle' fill='%23d9ef8a' font-family='Georgia' font-size='29'%3Es%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script src="/site.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Steady and True home"><span class="brand-mark" aria-hidden="true">s&t</span><span>${brand}<small>COACHING WITH JOSH BARBEE</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="Main navigation">${links.map(([id,url,label])=>`<a href="${url}"${key===id?' aria-current="page"':''}>${label}</a>`).join('')}<a class="button header-button" href="/start/"${key==='start'?' aria-current="page"':''}>Start here</a></nav></header><main id="main">${p.body}</main><footer><div><a class="footer-brand" href="/">${brand}</a><p>Grounded men. Stronger relationships.</p></div><div class="footer-links"><a href="/approach/">Our approach</a><a href="/coaching/">Coaching</a><a href="/start/">Start here</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Steady &amp; True · Josh Barbee</span><span>Coaching for growth. Grounded in respect.</span></div></footer></body></html>`}
// Additional pages are included in the same static build.
Object.assign(pages,additionalPages);
for(const [key,p] of Object.entries(pages)){const dir=key==='home'?'dist':`dist/${key}`;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(`${dir}/index.html`,render(key,p));}
console.log(`Built ${Object.keys(pages).length} pages.`);
