import fs from 'node:fs';
import home from './home.mjs';
import additionalPages from './pages.mjs';
const brand = 'Steady &amp; True';
const pages = { home };
function render(key,p){const links=[['home','/','Home'],['approach','/approach/','Our approach'],['coaching','/coaching/','Coaching']];return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#1d211e"><meta name="description" content="${p.description}"><title>${p.title} | Steady &amp; True</title><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' rx='1' fill='%231d211e'/%3E%3Ctext x='20' y='28' text-anchor='middle' fill='%23d4a56a' font-family='Arial' font-weight='bold' font-size='29'%3ES%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script src="/site.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="Steady and True home"><span class="brand-mark" aria-hidden="true">S&T</span><span>${brand}<small>COACHING WITH JOSH BARBEE</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="Main navigation">${links.map(([id,url,label])=>`<a href="${url}"${key===id?' aria-current="page"':''}>${label}</a>`).join('')}<a class="button header-button" href="/start/"${key==='start'?' aria-current="page"':''}>Start here</a></nav></header><main id="main">${p.body}</main><footer><div><a class="footer-brand" href="/">${brand}</a><p>We start with the man.</p></div><div class="footer-links"><a href="/approach/">Our approach</a><a href="/coaching/">Coaching</a><a href="/start/">Start here</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Steady &amp; True · Josh Barbee</span><span>His word. His week. His house.</span></div></footer></body></html>`}
// Additional pages are included in the same static build.
Object.assign(pages,additionalPages);
for(const [key,p] of Object.entries(pages)){const dir=key==='home'?'dist':`dist/${key}`;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(`${dir}/index.html`,render(key,p));}
console.log(`Built ${Object.keys(pages).length} pages.`);
